# -*- coding: utf-8 -*-
"""UI configuration and default hyperparameters for the training page."""

DEFAULT_TEST_SIZE = 0.2
DEFAULT_RANDOM_STATE = 42
DEFAULT_OPTUNA_TRIALS = 50
INVERSE_DESIGN_SPACE = {}


def _slider(name, label, default, min_value, max_value, step, help_text=None):
    item = {
        "name": name,
        "widget": "slider",
        "label": label,
        "default": default,
        "args": {
            "min_value": min_value,
            "max_value": max_value,
            "step": step,
        },
    }
    if help_text:
        item["help"] = help_text
    return item


def _number(name, label, default, min_value, max_value, step, fmt=None, help_text=None):
    args = {
        "min_value": min_value,
        "max_value": max_value,
        "step": step,
    }
    if fmt:
        args["format"] = fmt
    item = {
        "name": name,
        "widget": "number_input",
        "label": label,
        "default": default,
        "args": args,
    }
    if help_text:
        item["help"] = help_text
    return item


def _select(name, label, default, options, help_text=None):
    item = {
        "name": name,
        "widget": "selectbox",
        "label": label,
        "default": default,
        "args": {"options": list(options)},
    }
    if help_text:
        item["help"] = help_text
    return item


def _text(name, label, default, help_text=None):
    item = {
        "name": name,
        "widget": "text_input",
        "label": label,
        "default": default,
        "args": {},
    }
    if help_text:
        item["help"] = help_text
    return item


def _check(name, label, default, help_text=None):
    item = {
        "name": name,
        "widget": "checkbox",
        "label": label,
        "default": default,
        "args": {},
    }
    if help_text:
        item["help"] = help_text
    return item


LINEAR_REGRESSION_DEFAULTS = {
    "fit_intercept": True,
    "positive": False,
}

RIDGE_DEFAULTS = {
    "alpha": 1.0,
    "fit_intercept": True,
    "solver": "auto",
    "tol": 0.0001,
    "max_iter": 1000,
    "positive": False,
}

LASSO_DEFAULTS = {
    "alpha": 0.001,
    "fit_intercept": True,
    "tol": 0.0001,
    "max_iter": 5000,
    "selection": "cyclic",
    "positive": False,
}

ELASTICNET_DEFAULTS = {
    "alpha": 0.001,
    "l1_ratio": 0.5,
    "fit_intercept": True,
    "max_iter": 5000,
    "selection": "cyclic",
}

DECISION_TREE_DEFAULTS = {
    "criterion": "squared_error",
    "max_depth": 12,
    "min_samples_split": 2,
    "min_samples_leaf": 1,
}

RANDOM_FOREST_DEFAULTS = {
    "n_estimators": 500,
    "max_depth": 0,
    "min_samples_split": 2,
    "min_samples_leaf": 1,
    "max_features": "sqrt",
    "bootstrap": True,
    "max_samples": 1.0,
    "oob_score": False,
    "warm_start": False,
    "verbose": 0,
}

EXTRA_TREES_DEFAULTS = {
    "n_estimators": 500,
    "max_depth": 0,
    "min_samples_split": 2,
    "min_samples_leaf": 1,
    "max_features": "sqrt",
    "bootstrap": False,
    "oob_score": False,
    "warm_start": False,
    "verbose": 0,
}

GRADIENT_BOOSTING_DEFAULTS = {
    "loss": "squared_error",
    "n_estimators": 300,
    "learning_rate": 0.05,
    "max_depth": 3,
    "subsample": 0.8,
    "max_features": None,
    "min_samples_split": 2,
    "min_samples_leaf": 1,
    "verbose": 0,
}

ADABOOST_DEFAULTS = {
    "n_estimators": 200,
    "learning_rate": 0.1,
    "loss": "square",
}

SVR_DEFAULTS = {
    "kernel": "rbf",
    "C": 100.0,
    "epsilon": 0.1,
    "gamma": "scale",
    "cache_size": 1000,
}

MLP_DEFAULTS = {
    "hidden_layer_sizes": "256,128,64",
    "activation": "relu",
    "solver": "adam",
    "alpha": 0.0001,
    "learning_rate_init": 0.001,
    "batch_size": 128,
    "max_iter": 800,
    "early_stopping": True,
    "validation_fraction": 0.1,
}

GPR_DEFAULTS = {
    "kernel": "RBF + White",
    "length_scale": 1.0,
    "noise_level": 0.1,
    "nu": 1.5,
    "alpha": 1e-6,
    "normalize_y": True,
    "n_restarts_optimizer": 3,
}

LOGISTIC_CLASSIFIER_DEFAULTS = {
    "C": 1.0,
    "penalty": "l2",
    "solver": "lbfgs",
    "max_iter": 2000,
    "class_weight": "balanced",
}

RANDOM_FOREST_CLASSIFIER_DEFAULTS = {
    "n_estimators": 500,
    "max_depth": 0,
    "min_samples_split": 2,
    "min_samples_leaf": 1,
    "max_features": "sqrt",
    "bootstrap": True,
    "max_samples": 1.0,
    "oob_score": False,
    "class_weight": "balanced",
    "warm_start": False,
    "verbose": 0,
}

XGBOOST_CLASSIFIER_DEFAULTS = {
    "n_estimators": 600,
    "max_depth": 6,
    "learning_rate": 0.05,
    "subsample": 0.9,
    "colsample_bytree": 0.8,
    "min_child_weight": 1.0,
    "gamma": 0.0,
    "reg_alpha": 0.0,
    "reg_lambda": 1.0,
    "early_stopping_rounds": 50,
    "eval_metric": "logloss",
    "max_bin": 256,
    "verbosity": 0,
}

LIGHTGBM_CLASSIFIER_DEFAULTS = {
    "n_estimators": 600,
    "num_leaves": 63,
    "max_depth": 8,
    "learning_rate": 0.05,
    "subsample": 0.9,
    "colsample_bytree": 0.8,
    "reg_alpha": 0.0,
    "reg_lambda": 0.0,
    "min_child_samples": 20,
    "class_weight": "balanced",
}

CATBOOST_CLASSIFIER_DEFAULTS = {
    "iterations": 600,
    "depth": 6,
    "learning_rate": 0.05,
    "l2_leaf_reg": 3.0,
    "subsample": 0.9,
    "bagging_temperature": 0.0,
    "loss_function": "Logloss",
    "verbose": 50,
}

XGBOOST_DEFAULTS = {
    "n_estimators": 600,
    "max_depth": 6,
    "learning_rate": 0.05,
    "subsample": 0.9,
    "colsample_bytree": 0.8,
    "min_child_weight": 3.0,
    "gamma": 0.0,
    "reg_alpha": 0.0,
    "reg_lambda": 1.0,
    "early_stopping_rounds": 50,
    "eval_metric": "rmse",
    "max_bin": 256,
    "verbosity": 0,
}

LIGHTGBM_DEFAULTS = {
    "n_estimators": 600,
    "num_leaves": 63,
    "max_depth": 8,
    "learning_rate": 0.05,
    "subsample": 0.9,
    "colsample_bytree": 0.8,
    "reg_alpha": 0.0,
    "reg_lambda": 0.0,
    "min_child_samples": 20,
    "verbose": -1,
}

CATBOOST_DEFAULTS = {
    "iterations": 600,
    "depth": 6,
    "learning_rate": 0.05,
    "l2_leaf_reg": 3.0,
    "subsample": 0.9,
    "bagging_temperature": 1.0,
    "loss_function": "RMSE",
    "verbose": 0,
}

ANN_DEFAULTS = {
    "hidden_layer_sizes": "256,128,64",
    "learning_rate": 0.001,
    "batch_size": 512,
    "epochs": 150,
    "device": "auto",
    "use_data_parallel": True,
    "scaler_type": "standard",
    "normalize_target": False,
    "random_state": 42,
    "verbose": True,
}

AUTOGLUON_DEFAULTS = {
    "time_limit": 60,
    "presets": "medium_quality",
    "num_gpus": 0,
    "num_cpus": 8,
}

AUTOSKLEARN_DEFAULTS = {
    "time_left_for_this_task": 120,
    "per_run_time_limit": 30,
    "ensemble_size": 50,
}

TPOT_DEFAULTS = {
    "max_time_mins": 3,
    "max_eval_time_mins": 1,
    "generations": 3,
    "population_size": 30,
}

FLAML_DEFAULTS = {
    "time_budget": 60,
    "metric": "r2",
}

CHEMSL_DEFAULTS = {
    "n_estimators": 200,
    "fast_mode": True,
    "max_depth": 0,
    "min_estimators": 50,
}

FASTPROP_DEFAULTS = {
    "max_iter": 300,
    "learning_rate": 0.05,
    "max_depth": 6,
    "l2_regularization": 0.0,
}

BNN_DEFAULTS = {
    "hidden_layer_sizes": "256,128,64",
    "activation": "relu",
    "dropout_rate": 0.15,
    "use_batch_norm": False,
    "batch_norm_momentum": 0.05,
    "learning_rate": 0.001,
    "weight_decay": 0.0001,
    "optimizer": "adamw",
    "batch_size": 256,
    "epochs": 200,
    "patience": 30,
    "validation_split": 0.1,
    "mc_samples": 50,
    "loss_name": "gaussian_nll",
    "min_logvar": -6.0,
    "max_logvar": 3.0,
    "gradient_clip_norm": 1.0,
    "scheduler_factor": 0.6,
    "scheduler_patience": 8,
    "min_learning_rate": 1e-6,
    "device": "auto",
    "random_state": 42,
    "verbose": True,
    "missing_value_strategy": "median",
    "missing_imputer_max_iter": 15,
    "missing_n_imputations": 5,
}

MISSING_VALUE_DEFAULTS = {
    "missing_value_strategy": "bayesian",
    "missing_imputer_max_iter": 15,
    "missing_n_imputations": 5,
}

TRANSFORMER_MISSINGNESS_DEFAULTS = {
    **MISSING_VALUE_DEFAULTS,
    "use_missingness_embedding": True,
    "use_missingness_attention": True,
}

FT_TRANSFORMER_DEFAULTS = {
    "d_token": 128,
    "n_blocks": 4,
    "attention_n_heads": 8,
    "attention_dropout": 0.1,
    "residual_dropout": 0.0,
    "ffn_d_hidden": 256,
    "ffn_dropout": 0.1,
    "token_dropout": 0.05,
    "activation": "gelu",
    "sub_attention_dim": 64,
    "sub_attention_dropout": 0.1,
    "sub_attention_temperature": 1.0,
    "feature_gate_type": "softmax",
    "feature_gate_scale": 1.0,
    "use_feature_residual": True,
    "pooling": "cls",
    "head_hidden_dim": 128,
    "layer_norm_eps": 1e-5,
    "learning_rate": 0.001,
    "weight_decay": 0.00001,
    "batch_size": 256,
    "epochs": 150,
    "patience": 20,
    "validation_split": 0.1,
    "loss_name": "mse",
    "gradient_clip_norm": 1.0,
    "device": "auto",
    "seed": 42,
    **TRANSFORMER_MISSINGNESS_DEFAULTS,
}

TRANSFORMER_BNN_DEFAULTS = {
    **FT_TRANSFORMER_DEFAULTS,
    "missing_value_strategy": "median",
    "optimizer": "adamw",
    "weight_decay": 0.0001,
    "epochs": 200,
    "patience": 30,
    "mc_samples": 50,
    "loss_name": "gaussian_nll",
    "min_logvar": -6.0,
    "max_logvar": 3.0,
    "scheduler_factor": 0.6,
    "scheduler_patience": 8,
    "min_learning_rate": 1e-6,
    "use_data_parallel": False,
    "gpu_ids": "0,1",
    "random_state": 42,
    "verbose": True,
}
TRANSFORMER_BNN_DEFAULTS.pop("seed", None)

EPOXY_PINN_DEFAULTS = {
    "mode": "tg",
    "optimizer": "adamw",
    "hidden_dim": 768,
    "n_layers": 6,
    "dropout": 0.35,
    "lr": 0.0002,
    "weight_decay": 0.0003,
    "batch_size": 64,
    "epochs": 1500,
    "patience": 150,
    "physics_weight": 0.001,
    "physics_formula": "standard",
    "grad_clip": 2.0,
    "device": "auto",
    "verbose": False,
    "seed": 42,
    "target_name": "",
    **MISSING_VALUE_DEFAULTS,
}

TRANSFORMER_PINN_DEFAULTS = {
    "mode": "tg",
    "d_token": 128,
    "n_blocks": 4,
    "attention_n_heads": 8,
    "attention_dropout": 0.1,
    "residual_dropout": 0.0,
    "ffn_d_hidden": 256,
    "ffn_dropout": 0.1,
    "token_dropout": 0.05,
    "activation": "gelu",
    "sub_attention_dim": 64,
    "sub_attention_dropout": 0.1,
    "sub_attention_temperature": 1.0,
    "feature_gate_type": "softmax",
    "feature_gate_scale": 1.0,
    "use_feature_residual": True,
    "pooling": "cls",
    "head_hidden_dim": 128,
    "layer_norm_eps": 1e-5,
    "optimizer": "adamw",
    "lr": 0.001,
    "weight_decay": 0.0001,
    "batch_size": 128,
    "epochs": 400,
    "patience": 60,
    "physics_weight": 0.002,
    "physics_formula": "standard",
    "grad_clip": 1.5,
    "device": "auto",
    "verbose": False,
    "seed": 42,
    "target_name": "",
    **TRANSFORMER_MISSINGNESS_DEFAULTS,
}

GNN_TRANSFORMER_FUSION_DEFAULTS = {
    "smiles_col": "resin_smiles",
    "graph_model_type": "gcn",
    "graph_hidden_dim": 128,
    "graph_num_layers": 3,
    "graph_dropout": 0.1,
    "graph_pooling": "mean",
    "gat_heads": 4,
    "d_token": 128,
    "n_blocks": 4,
    "attention_n_heads": 8,
    "attention_dropout": 0.1,
    "residual_dropout": 0.0,
    "ffn_d_hidden": 256,
    "ffn_dropout": 0.1,
    "token_dropout": 0.05,
    "activation": "gelu",
    "sub_attention_dim": 64,
    "sub_attention_dropout": 0.1,
    "sub_attention_temperature": 1.0,
    "feature_gate_type": "softmax",
    "feature_gate_scale": 1.0,
    "use_feature_residual": True,
    "transformer_pooling": "cls",
    "fusion_hidden_dim": 256,
    "layer_norm_eps": 1e-5,
    "learning_rate": 0.001,
    "weight_decay": 0.0001,
    "batch_size": 32,
    "epochs": 120,
    "patience": 20,
    "validation_split": 0.1,
    "loss_name": "mse",
    "gradient_clip_norm": 1.0,
    "scheduler_factor": 0.6,
    "scheduler_patience": 6,
    "min_learning_rate": 1e-6,
    "num_workers": 0,
    "device": "auto",
    "random_state": 42,
    "verbose": 0,
    **TRANSFORMER_MISSINGNESS_DEFAULTS,
}

TABNET_DEFAULTS = {
    "n_d": 16,
    "n_a": 16,
    "n_steps": 3,
    "gamma": 1.3,
    "n_independent": 2,
    "n_shared": 2,
    "lambda_sparse": 1e-3,
    "momentum": 0.02,
    "clip_value": 1.0,
    "learning_rate": 0.003,
    "max_epochs": 200,
    "patience": 20,
    "batch_size": 256,
    "virtual_batch_size": 64,
    "mask_type": "sparsemax",
    "seed": 42,
}


MODEL_PARAMETERS = {
    "线性回归": dict(LINEAR_REGRESSION_DEFAULTS),
    "Ridge回归": dict(RIDGE_DEFAULTS),
    "Lasso回归": dict(LASSO_DEFAULTS),
    "ElasticNet": dict(ELASTICNET_DEFAULTS),
    "决策树": dict(DECISION_TREE_DEFAULTS),
    "随机森林": dict(RANDOM_FOREST_DEFAULTS),
    "Extra Trees": dict(EXTRA_TREES_DEFAULTS),
    "梯度提升树": dict(GRADIENT_BOOSTING_DEFAULTS),
    "AdaBoost": dict(ADABOOST_DEFAULTS),
    "SVR": dict(SVR_DEFAULTS),
    "多层感知器": dict(MLP_DEFAULTS),
    "Gaussian Process (GPR)": dict(GPR_DEFAULTS),
    "逻辑回归分类": dict(LOGISTIC_CLASSIFIER_DEFAULTS),
    "随机森林分类": dict(RANDOM_FOREST_CLASSIFIER_DEFAULTS),
    "XGBoost分类": dict(XGBOOST_CLASSIFIER_DEFAULTS),
    "LightGBM分类": dict(LIGHTGBM_CLASSIFIER_DEFAULTS),
    "CatBoost分类": dict(CATBOOST_CLASSIFIER_DEFAULTS),
    "XGBoost": dict(XGBOOST_DEFAULTS),
    "LightGBM": dict(LIGHTGBM_DEFAULTS),
    "CatBoost": dict(CATBOOST_DEFAULTS),
    "人工神经网络": dict(ANN_DEFAULTS),
    "Bayesian Neural Network (BNN)": dict(BNN_DEFAULTS),
    "FT-Transformer": dict(FT_TRANSFORMER_DEFAULTS),
    "Transformer + BNN": dict(TRANSFORMER_BNN_DEFAULTS),
    "Epoxy PINN (Physics-Informed)": dict(EPOXY_PINN_DEFAULTS),
    "Transformer + PINN": dict(TRANSFORMER_PINN_DEFAULTS),
    "GNN + Transformer Fusion": dict(GNN_TRANSFORMER_FUSION_DEFAULTS),
    "TabNet": dict(TABNET_DEFAULTS),
    "TensorFlow Sequential": {},
    "TabPFN": {},
    "AutoGluon": dict(AUTOGLUON_DEFAULTS),
    "Auto-sklearn": dict(AUTOSKLEARN_DEFAULTS),
    "TPOT": dict(TPOT_DEFAULTS),
    "FLAML": dict(FLAML_DEFAULTS),
    "Chemical SuperLearner (ChemSL)": dict(CHEMSL_DEFAULTS),
    "fastprop": dict(FASTPROP_DEFAULTS),
}


MODEL_SCOPE_GUIDE = {
    "线性回归": "Ordinary least-squares baseline with optional non-negative coefficients.",
    "Ridge回归": "L2-regularized linear regression for stable fitting under collinearity.",
    "Lasso回归": "L1-regularized sparse linear regression for feature selection and shrinkage.",
    "ElasticNet": "Mixed L1/L2 linear regression balancing sparsity and coefficient stability.",
    "决策树": "Single regression tree for fast interpretable nonlinear splits.",
    "随机森林": "Bagged ensemble of regression trees for robust nonlinear tabular prediction.",
    "Extra Trees": "More randomized tree ensemble that often trains faster and resists overfitting.",
    "梯度提升树": "Stage-wise boosted trees suitable for medium-scale structured regression.",
    "AdaBoost": "Adaptive boosting over shallow regressors for lightweight nonlinear modeling.",
    "SVR": "Kernel support-vector regression for smooth nonlinear fits, especially on smaller datasets.",
    "多层感知器": "Sklearn MLP baseline for dense nonlinear regression on tabular features.",
    "Gaussian Process (GPR)": "Probabilistic kernel regression for small datasets with uncertainty-aware predictions.",
    "逻辑回归分类": "Binary classification baseline with calibrated linear decision boundary and interpretable coefficients.",
    "随机森林分类": "Bagged tree classifier for robust nonlinear binary classification on tabular data.",
    "XGBoost分类": "Gradient-boosted binary classifier with strong performance on structured data.",
    "LightGBM分类": "Fast leaf-wise gradient boosting classifier for larger tabular binary classification tasks.",
    "CatBoost分类": "Regularized boosted-tree classifier with stable out-of-the-box binary classification behavior.",
    "XGBoost": "High-performance gradient boosting with strong accuracy on structured data.",
    "LightGBM": "Leaf-wise gradient boosting optimized for speed and larger tabular datasets.",
    "CatBoost": "Boosted trees with strong out-of-the-box behavior and robust regularization.",
    "人工神经网络": "PyTorch feed-forward neural network baseline with optional multi-GPU training.",
    "Bayesian Neural Network (BNN)": "Tabular uncertainty regression with MC dropout and heteroscedastic loss.",
    "FT-Transformer": "Tabular Transformer with feature sub-attention for higher-order feature interactions.",
    "Transformer + BNN": "FT-Transformer encoder with Bayesian regression head for both interaction modeling and uncertainty estimation.",
    "Epoxy PINN (Physics-Informed)": "Physics-informed regression for Tg or mechanics tasks that benefit from domain equations and process priors.",
    "Transformer + PINN": "FT-Transformer encoder combined with physics-informed loss for data-driven learning under material constraints.",
    "GNN + Transformer Fusion": "Joint learning from SMILES graph structure and numeric process/formulation features.",
    "TabNet": "Sparse attentive tabular network suitable for medium-scale structured data.",
    "TensorFlow Sequential": "Classic dense neural network baseline.",
    "TabPFN": "Fast prior-fitted tabular foundation model for small datasets.",
    "AutoGluon": "Automated tabular ensembling and model selection.",
    "Auto-sklearn": "Budgeted automated model search and ensembling for classic tabular regression.",
    "TPOT": "Genetic-programming AutoML pipeline search for structured regression tasks.",
    "FLAML": "Lightweight cost-aware AutoML optimized for fast model selection.",
    "Chemical SuperLearner (ChemSL)": "Stacked tree ensemble tuned for robust chemistry and materials tabular prediction.",
    "fastprop": "Fast HistGradientBoosting baseline for quick nonlinear regression benchmarking.",
}


MANUAL_TUNING_PARAMS = {
    "线性回归": [
        _check("fit_intercept", "Fit Intercept", LINEAR_REGRESSION_DEFAULTS["fit_intercept"]),
        _check("positive", "Positive Coefficients", LINEAR_REGRESSION_DEFAULTS["positive"]),
    ],
    "Ridge回归": [
        _number("alpha", "Alpha", RIDGE_DEFAULTS["alpha"], 0.0001, 100.0, 0.0001, "%.4f"),
        _check("fit_intercept", "Fit Intercept", RIDGE_DEFAULTS["fit_intercept"]),
        _select("solver", "Solver", RIDGE_DEFAULTS["solver"], ["auto", "svd", "cholesky", "lsqr", "sparse_cg", "sag", "saga", "lbfgs"]),
        _number("tol", "Tolerance", RIDGE_DEFAULTS["tol"], 0.000001, 0.1, 0.0001, "%.6f"),
        _slider("max_iter", "Max Iterations", RIDGE_DEFAULTS["max_iter"], 100, 10000, 100),
        _check("positive", "Positive Coefficients", RIDGE_DEFAULTS["positive"]),
    ],
    "Lasso回归": [
        _number("alpha", "Alpha", LASSO_DEFAULTS["alpha"], 0.0001, 10.0, 0.0001, "%.4f"),
        _check("fit_intercept", "Fit Intercept", LASSO_DEFAULTS["fit_intercept"]),
        _number("tol", "Tolerance", LASSO_DEFAULTS["tol"], 0.000001, 0.1, 0.0001, "%.6f"),
        _slider("max_iter", "Max Iterations", LASSO_DEFAULTS["max_iter"], 500, 10000, 100),
        _select("selection", "Coordinate Selection", LASSO_DEFAULTS["selection"], ["cyclic", "random"]),
        _check("positive", "Positive Coefficients", LASSO_DEFAULTS["positive"]),
    ],
    "ElasticNet": [
        _number("alpha", "Alpha", ELASTICNET_DEFAULTS["alpha"], 0.0001, 10.0, 0.0001, "%.4f"),
        _slider("l1_ratio", "L1 Ratio", ELASTICNET_DEFAULTS["l1_ratio"], 0.0, 1.0, 0.05),
        _check("fit_intercept", "Fit Intercept", ELASTICNET_DEFAULTS["fit_intercept"]),
        _slider("max_iter", "Max Iterations", ELASTICNET_DEFAULTS["max_iter"], 500, 10000, 100),
        _select("selection", "Coordinate Selection", ELASTICNET_DEFAULTS["selection"], ["cyclic", "random"]),
    ],
    "决策树": [
        _select("criterion", "Criterion", DECISION_TREE_DEFAULTS["criterion"], ["squared_error", "friedman_mse", "absolute_error"]),
        _slider("max_depth", "Max Depth", DECISION_TREE_DEFAULTS["max_depth"], 1, 40, 1),
        _slider("min_samples_split", "Min Samples Split", DECISION_TREE_DEFAULTS["min_samples_split"], 2, 40, 1),
        _slider("min_samples_leaf", "Min Samples Leaf", DECISION_TREE_DEFAULTS["min_samples_leaf"], 1, 20, 1),
    ],
    "随机森林": [
        _slider("n_estimators", "Number of Trees", RANDOM_FOREST_DEFAULTS["n_estimators"], 50, 2000, 50),
        _slider("max_depth", "Max Depth (0=None)", RANDOM_FOREST_DEFAULTS["max_depth"], 0, 40, 1),
        _slider("min_samples_split", "Min Samples Split", RANDOM_FOREST_DEFAULTS["min_samples_split"], 2, 40, 1),
        _slider("min_samples_leaf", "Min Samples Leaf", RANDOM_FOREST_DEFAULTS["min_samples_leaf"], 1, 20, 1),
        _select("max_features", "Max Features", RANDOM_FOREST_DEFAULTS["max_features"], ["sqrt", "log2", None]),
        _check("bootstrap", "Bootstrap Sampling", RANDOM_FOREST_DEFAULTS["bootstrap"]),
        _number("max_samples", "Bootstrap Sample Ratio", RANDOM_FOREST_DEFAULTS["max_samples"], 0.1, 1.0, 0.05, "%.2f", "Fraction of rows used by each tree when bootstrap sampling is enabled."),
        _check("oob_score", "Enable OOB Score", RANDOM_FOREST_DEFAULTS["oob_score"]),
        _check("warm_start", "Warm Start", RANDOM_FOREST_DEFAULTS["warm_start"]),
        _slider("verbose", "Verbose Level", RANDOM_FOREST_DEFAULTS["verbose"], 0, 2, 1),
    ],
    "Extra Trees": [
        _slider("n_estimators", "Number of Trees", EXTRA_TREES_DEFAULTS["n_estimators"], 50, 2000, 50),
        _slider("max_depth", "Max Depth (0=None)", EXTRA_TREES_DEFAULTS["max_depth"], 0, 40, 1),
        _slider("min_samples_split", "Min Samples Split", EXTRA_TREES_DEFAULTS["min_samples_split"], 2, 40, 1),
        _slider("min_samples_leaf", "Min Samples Leaf", EXTRA_TREES_DEFAULTS["min_samples_leaf"], 1, 20, 1),
        _select("max_features", "Max Features", EXTRA_TREES_DEFAULTS["max_features"], ["sqrt", "log2", None]),
        _check("bootstrap", "Bootstrap Sampling", EXTRA_TREES_DEFAULTS["bootstrap"]),
        _check("oob_score", "Enable OOB Score", EXTRA_TREES_DEFAULTS["oob_score"]),
        _check("warm_start", "Warm Start", EXTRA_TREES_DEFAULTS["warm_start"]),
        _slider("verbose", "Verbose Level", EXTRA_TREES_DEFAULTS["verbose"], 0, 2, 1),
    ],
    "梯度提升树": [
        _select("loss", "Loss Function", GRADIENT_BOOSTING_DEFAULTS["loss"], ["squared_error", "absolute_error", "huber", "quantile"]),
        _slider("n_estimators", "Number of Trees", GRADIENT_BOOSTING_DEFAULTS["n_estimators"], 50, 1500, 50),
        _number("learning_rate", "Learning Rate", GRADIENT_BOOSTING_DEFAULTS["learning_rate"], 0.001, 0.5, 0.001, "%.3f"),
        _slider("max_depth", "Tree Depth", GRADIENT_BOOSTING_DEFAULTS["max_depth"], 1, 10, 1),
        _slider("subsample", "Subsample", GRADIENT_BOOSTING_DEFAULTS["subsample"], 0.3, 1.0, 0.05),
        _select("max_features", "Max Features", GRADIENT_BOOSTING_DEFAULTS["max_features"], [None, 1.0, 0.7, 0.5, "sqrt", "log2"]),
        _slider("min_samples_split", "Min Samples Split", GRADIENT_BOOSTING_DEFAULTS["min_samples_split"], 2, 40, 1),
        _slider("min_samples_leaf", "Min Samples Leaf", GRADIENT_BOOSTING_DEFAULTS["min_samples_leaf"], 1, 20, 1),
        _slider("verbose", "Verbose Level", GRADIENT_BOOSTING_DEFAULTS["verbose"], 0, 2, 1),
    ],
    "AdaBoost": [
        _slider("n_estimators", "Number of Estimators", ADABOOST_DEFAULTS["n_estimators"], 50, 1500, 50),
        _number("learning_rate", "Learning Rate", ADABOOST_DEFAULTS["learning_rate"], 0.001, 2.0, 0.001, "%.3f"),
        _select("loss", "Loss Function", ADABOOST_DEFAULTS["loss"], ["linear", "square", "exponential"]),
    ],
    "SVR": [
        _select("kernel", "Kernel", SVR_DEFAULTS["kernel"], ["rbf", "linear", "poly", "sigmoid"]),
        _number("C", "Penalty C", SVR_DEFAULTS["C"], 0.1, 1000.0, 0.1, "%.1f"),
        _number("epsilon", "Epsilon", SVR_DEFAULTS["epsilon"], 0.001, 1.0, 0.001, "%.3f"),
        _select("gamma", "Gamma", SVR_DEFAULTS["gamma"], ["scale", "auto"]),
        _slider("cache_size", "Kernel Cache Size (MB)", SVR_DEFAULTS["cache_size"], 100, 4000, 100),
    ],
    "多层感知器": [
        _text("hidden_layer_sizes", "Hidden Layer Sizes", MLP_DEFAULTS["hidden_layer_sizes"], "Comma-separated widths, for example 256,128,64."),
        _select("activation", "Activation", MLP_DEFAULTS["activation"], ["relu", "tanh", "logistic", "identity"]),
        _select("solver", "Solver", MLP_DEFAULTS["solver"], ["adam", "lbfgs", "sgd"]),
        _number("alpha", "L2 Regularization", MLP_DEFAULTS["alpha"], 0.0, 0.1, 0.0001, "%.4f"),
        _number("learning_rate_init", "Learning Rate", MLP_DEFAULTS["learning_rate_init"], 0.00001, 0.1, 0.00001, "%.5f"),
        _slider("batch_size", "Batch Size", MLP_DEFAULTS["batch_size"], 16, 512, 16),
        _slider("max_iter", "Max Iterations", MLP_DEFAULTS["max_iter"], 100, 3000, 50),
        _check("early_stopping", "Early Stopping", MLP_DEFAULTS["early_stopping"]),
        _slider("validation_fraction", "Validation Fraction", MLP_DEFAULTS["validation_fraction"], 0.05, 0.3, 0.05),
    ],
    "Gaussian Process (GPR)": [
        _select("kernel", "Kernel", GPR_DEFAULTS["kernel"], ["RBF + White", "Matern + White", "RationalQuadratic + White", "RBF", "Matern", "RationalQuadratic"]),
        _number("length_scale", "Length Scale", GPR_DEFAULTS["length_scale"], 0.001, 100.0, 0.001, "%.3f"),
        _number("noise_level", "Noise Level", GPR_DEFAULTS["noise_level"], 0.000001, 10.0, 0.000001, "%.6f"),
        _number("nu", "Matern Nu", GPR_DEFAULTS["nu"], 0.5, 2.5, 0.5, "%.1f"),
        _number("alpha", "Alpha", GPR_DEFAULTS["alpha"], 0.0000001, 1.0, 0.0000001, "%.7f"),
        _check("normalize_y", "Normalize Target", GPR_DEFAULTS["normalize_y"]),
        _slider("n_restarts_optimizer", "Optimizer Restarts", GPR_DEFAULTS["n_restarts_optimizer"], 0, 20, 1),
    ],
    "逻辑回归分类": [
        _number("C", "Inverse Regularization Strength", LOGISTIC_CLASSIFIER_DEFAULTS["C"], 0.01, 100.0, 0.01, "%.2f"),
        _select("penalty", "Penalty", LOGISTIC_CLASSIFIER_DEFAULTS["penalty"], ["l2", "l1"]),
        _select("solver", "Solver", LOGISTIC_CLASSIFIER_DEFAULTS["solver"], ["lbfgs", "liblinear", "saga"]),
        _slider("max_iter", "Max Iterations", LOGISTIC_CLASSIFIER_DEFAULTS["max_iter"], 200, 5000, 100),
        _select("class_weight", "Class Weight", LOGISTIC_CLASSIFIER_DEFAULTS["class_weight"], [None, "balanced"]),
    ],
    "随机森林分类": [
        _slider("n_estimators", "Number of Trees", RANDOM_FOREST_CLASSIFIER_DEFAULTS["n_estimators"], 50, 2000, 50),
        _slider("max_depth", "Max Depth (0=None)", RANDOM_FOREST_CLASSIFIER_DEFAULTS["max_depth"], 0, 40, 1),
        _slider("min_samples_split", "Min Samples Split", RANDOM_FOREST_CLASSIFIER_DEFAULTS["min_samples_split"], 2, 40, 1),
        _slider("min_samples_leaf", "Min Samples Leaf", RANDOM_FOREST_CLASSIFIER_DEFAULTS["min_samples_leaf"], 1, 20, 1),
        _select("max_features", "Max Features", RANDOM_FOREST_CLASSIFIER_DEFAULTS["max_features"], ["sqrt", "log2", None]),
        _check("bootstrap", "Bootstrap Sampling", RANDOM_FOREST_CLASSIFIER_DEFAULTS["bootstrap"]),
        _number("max_samples", "Bootstrap Sample Ratio", RANDOM_FOREST_CLASSIFIER_DEFAULTS["max_samples"], 0.1, 1.0, 0.05, "%.2f"),
        _check("oob_score", "Enable OOB Score", RANDOM_FOREST_CLASSIFIER_DEFAULTS["oob_score"]),
        _select("class_weight", "Class Weight", RANDOM_FOREST_CLASSIFIER_DEFAULTS["class_weight"], [None, "balanced", "balanced_subsample"]),
        _check("warm_start", "Warm Start", RANDOM_FOREST_CLASSIFIER_DEFAULTS["warm_start"]),
        _slider("verbose", "Verbose Level", RANDOM_FOREST_CLASSIFIER_DEFAULTS["verbose"], 0, 2, 1),
    ],
    "XGBoost分类": [
        _slider("n_estimators", "Number of Trees", XGBOOST_CLASSIFIER_DEFAULTS["n_estimators"], 50, 3000, 50),
        _slider("max_depth", "Max Depth", XGBOOST_CLASSIFIER_DEFAULTS["max_depth"], 2, 16, 1),
        _number("learning_rate", "Learning Rate", XGBOOST_CLASSIFIER_DEFAULTS["learning_rate"], 0.001, 0.3, 0.001, "%.3f"),
        _slider("subsample", "Subsample", XGBOOST_CLASSIFIER_DEFAULTS["subsample"], 0.3, 1.0, 0.05),
        _slider("colsample_bytree", "Column Sample by Tree", XGBOOST_CLASSIFIER_DEFAULTS["colsample_bytree"], 0.3, 1.0, 0.05),
        _number("min_child_weight", "Min Child Weight", XGBOOST_CLASSIFIER_DEFAULTS["min_child_weight"], 0.0, 20.0, 0.5, "%.1f"),
        _number("gamma", "Gamma", XGBOOST_CLASSIFIER_DEFAULTS["gamma"], 0.0, 10.0, 0.1, "%.1f"),
        _number("reg_alpha", "L1 Regularization", XGBOOST_CLASSIFIER_DEFAULTS["reg_alpha"], 0.0, 10.0, 0.1, "%.1f"),
        _number("reg_lambda", "L2 Regularization", XGBOOST_CLASSIFIER_DEFAULTS["reg_lambda"], 0.0, 20.0, 0.1, "%.1f"),
        _slider("early_stopping_rounds", "Early Stopping Rounds", XGBOOST_CLASSIFIER_DEFAULTS["early_stopping_rounds"], 0, 300, 10),
        _select("eval_metric", "Eval Metric", XGBOOST_CLASSIFIER_DEFAULTS["eval_metric"], ["logloss", "auc", "error"]),
        _slider("max_bin", "Max Bins", XGBOOST_CLASSIFIER_DEFAULTS["max_bin"], 64, 1024, 64),
        _slider("verbosity", "Verbose Level", XGBOOST_CLASSIFIER_DEFAULTS["verbosity"], 0, 3, 1),
    ],
    "LightGBM分类": [
        _slider("n_estimators", "Number of Trees", LIGHTGBM_CLASSIFIER_DEFAULTS["n_estimators"], 50, 3000, 50),
        _slider("num_leaves", "Number of Leaves", LIGHTGBM_CLASSIFIER_DEFAULTS["num_leaves"], 8, 255, 1),
        _slider("max_depth", "Max Depth", LIGHTGBM_CLASSIFIER_DEFAULTS["max_depth"], -1, 20, 1),
        _number("learning_rate", "Learning Rate", LIGHTGBM_CLASSIFIER_DEFAULTS["learning_rate"], 0.001, 0.3, 0.001, "%.3f"),
        _slider("subsample", "Subsample", LIGHTGBM_CLASSIFIER_DEFAULTS["subsample"], 0.3, 1.0, 0.05),
        _slider("colsample_bytree", "Column Sample by Tree", LIGHTGBM_CLASSIFIER_DEFAULTS["colsample_bytree"], 0.3, 1.0, 0.05),
        _number("reg_alpha", "L1 Regularization", LIGHTGBM_CLASSIFIER_DEFAULTS["reg_alpha"], 0.0, 10.0, 0.1, "%.1f"),
        _number("reg_lambda", "L2 Regularization", LIGHTGBM_CLASSIFIER_DEFAULTS["reg_lambda"], 0.0, 20.0, 0.1, "%.1f"),
        _slider("min_child_samples", "Min Child Samples", LIGHTGBM_CLASSIFIER_DEFAULTS["min_child_samples"], 2, 100, 1),
        _select("class_weight", "Class Weight", LIGHTGBM_CLASSIFIER_DEFAULTS["class_weight"], [None, "balanced"]),
    ],
    "CatBoost分类": [
        _slider("iterations", "Iterations", CATBOOST_CLASSIFIER_DEFAULTS["iterations"], 50, 3000, 50),
        _slider("depth", "Tree Depth", CATBOOST_CLASSIFIER_DEFAULTS["depth"], 2, 12, 1),
        _number("learning_rate", "Learning Rate", CATBOOST_CLASSIFIER_DEFAULTS["learning_rate"], 0.001, 0.3, 0.001, "%.3f"),
        _number("l2_leaf_reg", "L2 Leaf Regularization", CATBOOST_CLASSIFIER_DEFAULTS["l2_leaf_reg"], 0.0, 20.0, 0.1, "%.1f"),
        _slider("subsample", "Subsample", CATBOOST_CLASSIFIER_DEFAULTS["subsample"], 0.3, 1.0, 0.05),
        _number("bagging_temperature", "Bagging Temperature", CATBOOST_CLASSIFIER_DEFAULTS["bagging_temperature"], 0.0, 5.0, 0.1, "%.1f"),
        _select("loss_function", "Loss Function", CATBOOST_CLASSIFIER_DEFAULTS["loss_function"], ["Logloss", "CrossEntropy"]),
        _slider("verbose", "Verbose Interval", CATBOOST_CLASSIFIER_DEFAULTS["verbose"], 0, 200, 10),
    ],
    "XGBoost": [
        _slider("n_estimators", "Number of Trees", XGBOOST_DEFAULTS["n_estimators"], 50, 3000, 50),
        _slider("max_depth", "Max Depth", XGBOOST_DEFAULTS["max_depth"], 2, 16, 1),
        _number("learning_rate", "Learning Rate", XGBOOST_DEFAULTS["learning_rate"], 0.001, 0.3, 0.001, "%.3f"),
        _slider("subsample", "Subsample", XGBOOST_DEFAULTS["subsample"], 0.3, 1.0, 0.05),
        _slider("colsample_bytree", "Column Sample by Tree", XGBOOST_DEFAULTS["colsample_bytree"], 0.3, 1.0, 0.05),
        _number("min_child_weight", "Min Child Weight", XGBOOST_DEFAULTS["min_child_weight"], 0.0, 20.0, 0.5, "%.1f"),
        _number("gamma", "Gamma", XGBOOST_DEFAULTS["gamma"], 0.0, 10.0, 0.1, "%.1f"),
        _number("reg_alpha", "L1 Regularization", XGBOOST_DEFAULTS["reg_alpha"], 0.0, 10.0, 0.1, "%.1f"),
        _number("reg_lambda", "L2 Regularization", XGBOOST_DEFAULTS["reg_lambda"], 0.0, 20.0, 0.1, "%.1f"),
        _slider("early_stopping_rounds", "Early Stopping Rounds", XGBOOST_DEFAULTS["early_stopping_rounds"], 0, 300, 10),
        _select("eval_metric", "Eval Metric", XGBOOST_DEFAULTS["eval_metric"], ["rmse", "mae", "mape", "rmsle"]),
        _slider("max_bin", "Max Bins", XGBOOST_DEFAULTS["max_bin"], 64, 1024, 64),
        _slider("verbosity", "Verbose Level", XGBOOST_DEFAULTS["verbosity"], 0, 3, 1),
    ],
    "LightGBM": [
        _slider("n_estimators", "Number of Trees", LIGHTGBM_DEFAULTS["n_estimators"], 50, 3000, 50),
        _slider("num_leaves", "Number of Leaves", LIGHTGBM_DEFAULTS["num_leaves"], 8, 255, 1),
        _slider("max_depth", "Max Depth", LIGHTGBM_DEFAULTS["max_depth"], -1, 20, 1),
        _number("learning_rate", "Learning Rate", LIGHTGBM_DEFAULTS["learning_rate"], 0.001, 0.3, 0.001, "%.3f"),
        _slider("subsample", "Subsample", LIGHTGBM_DEFAULTS["subsample"], 0.3, 1.0, 0.05),
        _slider("colsample_bytree", "Column Sample by Tree", LIGHTGBM_DEFAULTS["colsample_bytree"], 0.3, 1.0, 0.05),
        _number("reg_alpha", "L1 Regularization", LIGHTGBM_DEFAULTS["reg_alpha"], 0.0, 10.0, 0.1, "%.1f"),
        _number("reg_lambda", "L2 Regularization", LIGHTGBM_DEFAULTS["reg_lambda"], 0.0, 20.0, 0.1, "%.1f"),
        _slider("min_child_samples", "Min Child Samples", LIGHTGBM_DEFAULTS["min_child_samples"], 2, 100, 1),
    ],
    "CatBoost": [
        _slider("iterations", "Iterations", CATBOOST_DEFAULTS["iterations"], 50, 3000, 50),
        _slider("depth", "Tree Depth", CATBOOST_DEFAULTS["depth"], 2, 12, 1),
        _number("learning_rate", "Learning Rate", CATBOOST_DEFAULTS["learning_rate"], 0.001, 0.3, 0.001, "%.3f"),
        _number("l2_leaf_reg", "L2 Leaf Regularization", CATBOOST_DEFAULTS["l2_leaf_reg"], 0.0, 20.0, 0.1, "%.1f"),
        _slider("subsample", "Subsample", CATBOOST_DEFAULTS["subsample"], 0.3, 1.0, 0.05),
        _number("bagging_temperature", "Bagging Temperature", CATBOOST_DEFAULTS["bagging_temperature"], 0.0, 5.0, 0.1, "%.1f"),
        _select("loss_function", "Loss Function", CATBOOST_DEFAULTS["loss_function"], ["RMSE", "MAE", "Huber", "Quantile"]),
        _slider("verbose", "Verbose Interval", CATBOOST_DEFAULTS["verbose"], 0, 200, 10),
    ],
    "人工神经网络": [
        _text("hidden_layer_sizes", "Hidden Layer Sizes", ANN_DEFAULTS["hidden_layer_sizes"], "Comma-separated widths, for example 256,128,64."),
        _number("learning_rate", "Learning Rate", ANN_DEFAULTS["learning_rate"], 0.00001, 0.05, 0.00001, "%.5f"),
        _slider("batch_size", "Batch Size", ANN_DEFAULTS["batch_size"], 32, 4096, 32),
        _slider("epochs", "Epochs", ANN_DEFAULTS["epochs"], 20, 1000, 20),
        _select("device", "Device", ANN_DEFAULTS["device"], ["auto", "cpu", "cuda"]),
        _check("use_data_parallel", "Use Multi-GPU DataParallel", ANN_DEFAULTS["use_data_parallel"]),
        _select("scaler_type", "Feature Scaler", ANN_DEFAULTS["scaler_type"], ["standard", "minmax", "robust"]),
        _check("normalize_target", "Normalize Target", ANN_DEFAULTS["normalize_target"]),
        _number("random_state", "Random Seed", ANN_DEFAULTS["random_state"], 0, 9999, 1),
        _check("verbose", "Verbose Logging", ANN_DEFAULTS["verbose"]),
    ],
    "Bayesian Neural Network (BNN)": [
        _text("hidden_layer_sizes", "Hidden Layer Sizes", BNN_DEFAULTS["hidden_layer_sizes"], "Comma-separated widths, for example 256,128,64."),
        _select("activation", "Activation", BNN_DEFAULTS["activation"], ["relu", "gelu", "silu", "elu", "tanh", "leaky_relu"]),
        _slider("dropout_rate", "Dropout", BNN_DEFAULTS["dropout_rate"], 0.0, 0.6, 0.05),
        _check("use_batch_norm", "Use BatchNorm", BNN_DEFAULTS["use_batch_norm"]),
        _number("batch_norm_momentum", "BatchNorm Momentum", BNN_DEFAULTS["batch_norm_momentum"], 0.01, 0.3, 0.01, "%.2f"),
        _select("optimizer", "Optimizer", BNN_DEFAULTS["optimizer"], ["adamw", "adam", "sgd", "rmsprop"]),
        _number("learning_rate", "Learning Rate", BNN_DEFAULTS["learning_rate"], 0.00001, 0.02, 0.00001, "%.5f"),
        _number("weight_decay", "Weight Decay", BNN_DEFAULTS["weight_decay"], 0.0, 0.01, 0.0001, "%.4f"),
        _slider("batch_size", "Batch Size", BNN_DEFAULTS["batch_size"], 16, 2048, 16),
        _slider("epochs", "Epochs", BNN_DEFAULTS["epochs"], 20, 800, 20),
        _slider("patience", "Early Stopping Patience", BNN_DEFAULTS["patience"], 5, 120, 5),
        _slider("validation_split", "Validation Split", BNN_DEFAULTS["validation_split"], 0.0, 0.3, 0.05),
        _slider("mc_samples", "MC Samples", BNN_DEFAULTS["mc_samples"], 5, 200, 5, "More samples improve uncertainty stability but slow inference."),
        _select("loss_name", "Loss Function", BNN_DEFAULTS["loss_name"], ["gaussian_nll", "mse"]),
        _number("min_logvar", "Min Log-Variance", BNN_DEFAULTS["min_logvar"], -12.0, -1.0, 0.5, "%.1f"),
        _number("max_logvar", "Max Log-Variance", BNN_DEFAULTS["max_logvar"], 0.5, 8.0, 0.5, "%.1f"),
        _number("gradient_clip_norm", "Gradient Clipping", BNN_DEFAULTS["gradient_clip_norm"], 0.0, 10.0, 0.5, "%.1f"),
        _select("missing_value_strategy", "Missing Value Strategy", BNN_DEFAULTS["missing_value_strategy"], ["median", "bayesian", "multiple_bayesian"]),
        _slider("missing_imputer_max_iter", "Imputer Max Iterations", BNN_DEFAULTS["missing_imputer_max_iter"], 5, 50, 1),
        _slider("missing_n_imputations", "Multiple Imputations", BNN_DEFAULTS["missing_n_imputations"], 2, 20, 1),
        _slider("scheduler_factor", "LR Scheduler Factor", BNN_DEFAULTS["scheduler_factor"], 0.1, 0.9, 0.1),
        _slider("scheduler_patience", "LR Scheduler Patience", BNN_DEFAULTS["scheduler_patience"], 2, 30, 1),
        _number("min_learning_rate", "Minimum Learning Rate", BNN_DEFAULTS["min_learning_rate"], 1e-7, 1e-4, 1e-7, "%.7f"),
        _select("device", "Device", BNN_DEFAULTS["device"], ["auto", "cpu", "cuda"]),
        _number("random_state", "Random Seed", BNN_DEFAULTS["random_state"], 0, 9999, 1),
        _check("verbose", "Verbose Logging", BNN_DEFAULTS["verbose"]),
    ],
    "FT-Transformer": [
        _slider("d_token", "Token Dimension", FT_TRANSFORMER_DEFAULTS["d_token"], 64, 512, 32),
        _slider("n_blocks", "Transformer Blocks", FT_TRANSFORMER_DEFAULTS["n_blocks"], 1, 8, 1),
        _slider("attention_n_heads", "Attention Heads", FT_TRANSFORMER_DEFAULTS["attention_n_heads"], 2, 16, 2),
        _slider("attention_dropout", "Attention Dropout", FT_TRANSFORMER_DEFAULTS["attention_dropout"], 0.0, 0.5, 0.05),
        _slider("residual_dropout", "Residual Dropout", FT_TRANSFORMER_DEFAULTS["residual_dropout"], 0.0, 0.4, 0.05),
        _slider("ffn_d_hidden", "FFN Hidden Dimension", FT_TRANSFORMER_DEFAULTS["ffn_d_hidden"], 128, 2048, 128),
        _slider("ffn_dropout", "FFN Dropout", FT_TRANSFORMER_DEFAULTS["ffn_dropout"], 0.0, 0.5, 0.05),
        _slider("token_dropout", "Token Dropout", FT_TRANSFORMER_DEFAULTS["token_dropout"], 0.0, 0.3, 0.05),
        _select("activation", "Activation", FT_TRANSFORMER_DEFAULTS["activation"], ["gelu", "relu", "silu", "elu", "tanh", "leaky_relu"]),
        _slider("sub_attention_dim", "Sub-Attention Hidden Dimension", FT_TRANSFORMER_DEFAULTS["sub_attention_dim"], 16, 256, 16),
        _slider("sub_attention_dropout", "Sub-Attention Dropout", FT_TRANSFORMER_DEFAULTS["sub_attention_dropout"], 0.0, 0.5, 0.05),
        _number("sub_attention_temperature", "Sub-Attention Temperature", FT_TRANSFORMER_DEFAULTS["sub_attention_temperature"], 0.2, 3.0, 0.1, "%.1f"),
        _select("feature_gate_type", "Feature Gate Type", FT_TRANSFORMER_DEFAULTS["feature_gate_type"], ["softmax", "sigmoid"]),
        _number("feature_gate_scale", "Feature Gate Scale", FT_TRANSFORMER_DEFAULTS["feature_gate_scale"], 0.1, 3.0, 0.1, "%.1f"),
        _check("use_feature_residual", "Use Feature Residual", FT_TRANSFORMER_DEFAULTS["use_feature_residual"]),
        _select("pooling", "Pooling", FT_TRANSFORMER_DEFAULTS["pooling"], ["cls", "mean", "attention"]),
        _slider("head_hidden_dim", "Prediction Head Hidden Dimension", FT_TRANSFORMER_DEFAULTS["head_hidden_dim"], 0, 512, 32),
        _number("layer_norm_eps", "LayerNorm Epsilon", FT_TRANSFORMER_DEFAULTS["layer_norm_eps"], 1e-6, 1e-3, 1e-6, "%.6f"),
        _number("learning_rate", "Learning Rate", FT_TRANSFORMER_DEFAULTS["learning_rate"], 1e-5, 1e-2, 1e-5, "%.5f"),
        _number("weight_decay", "Weight Decay", FT_TRANSFORMER_DEFAULTS["weight_decay"], 0.0, 0.01, 1e-6, "%.6f"),
        _slider("batch_size", "Batch Size", FT_TRANSFORMER_DEFAULTS["batch_size"], 16, 2048, 16),
        _slider("epochs", "Epochs", FT_TRANSFORMER_DEFAULTS["epochs"], 20, 800, 20),
        _slider("patience", "Early Stopping Patience", FT_TRANSFORMER_DEFAULTS["patience"], 5, 120, 5),
        _slider("validation_split", "Validation Split", FT_TRANSFORMER_DEFAULTS["validation_split"], 0.0, 0.3, 0.05),
        _select("loss_name", "Loss Function", FT_TRANSFORMER_DEFAULTS["loss_name"], ["mse", "huber", "mae"]),
        _number("gradient_clip_norm", "Gradient Clipping", FT_TRANSFORMER_DEFAULTS["gradient_clip_norm"], 0.0, 10.0, 0.5, "%.1f"),
        _select("missing_value_strategy", "Missing Value Strategy", FT_TRANSFORMER_DEFAULTS["missing_value_strategy"], ["median", "bayesian", "multiple_bayesian"]),
        _slider("missing_imputer_max_iter", "Imputer Max Iterations", FT_TRANSFORMER_DEFAULTS["missing_imputer_max_iter"], 5, 50, 1),
        _slider("missing_n_imputations", "Multiple Imputations", FT_TRANSFORMER_DEFAULTS["missing_n_imputations"], 2, 20, 1),
        _check("use_missingness_embedding", "Use Missingness Embedding", FT_TRANSFORMER_DEFAULTS["use_missingness_embedding"]),
        _check("use_missingness_attention", "Use Missingness Attention", FT_TRANSFORMER_DEFAULTS["use_missingness_attention"]),
        _select("device", "Device", FT_TRANSFORMER_DEFAULTS["device"], ["auto", "cpu", "cuda"]),
        _number("seed", "Random Seed", FT_TRANSFORMER_DEFAULTS["seed"], 0, 9999, 1),
    ],
    "Transformer + BNN": [
        _slider("d_token", "Token Dimension", TRANSFORMER_BNN_DEFAULTS["d_token"], 64, 512, 32),
        _slider("n_blocks", "Transformer Blocks", TRANSFORMER_BNN_DEFAULTS["n_blocks"], 1, 8, 1),
        _slider("attention_n_heads", "Attention Heads", TRANSFORMER_BNN_DEFAULTS["attention_n_heads"], 2, 16, 2),
        _slider("attention_dropout", "Attention Dropout", TRANSFORMER_BNN_DEFAULTS["attention_dropout"], 0.0, 0.5, 0.05),
        _slider("residual_dropout", "Residual Dropout", TRANSFORMER_BNN_DEFAULTS["residual_dropout"], 0.0, 0.4, 0.05),
        _slider("ffn_d_hidden", "FFN Hidden Dimension", TRANSFORMER_BNN_DEFAULTS["ffn_d_hidden"], 128, 2048, 128),
        _slider("ffn_dropout", "FFN Dropout", TRANSFORMER_BNN_DEFAULTS["ffn_dropout"], 0.0, 0.5, 0.05),
        _slider("token_dropout", "Token Dropout", TRANSFORMER_BNN_DEFAULTS["token_dropout"], 0.0, 0.3, 0.05),
        _select("activation", "Activation", TRANSFORMER_BNN_DEFAULTS["activation"], ["gelu", "relu", "silu", "elu", "tanh", "leaky_relu"]),
        _slider("sub_attention_dim", "Sub-Attention Hidden Dimension", TRANSFORMER_BNN_DEFAULTS["sub_attention_dim"], 16, 256, 16),
        _slider("sub_attention_dropout", "Sub-Attention Dropout", TRANSFORMER_BNN_DEFAULTS["sub_attention_dropout"], 0.0, 0.5, 0.05),
        _number("sub_attention_temperature", "Sub-Attention Temperature", TRANSFORMER_BNN_DEFAULTS["sub_attention_temperature"], 0.2, 3.0, 0.1, "%.1f"),
        _select("feature_gate_type", "Feature Gate Type", TRANSFORMER_BNN_DEFAULTS["feature_gate_type"], ["softmax", "sigmoid"]),
        _number("feature_gate_scale", "Feature Gate Scale", TRANSFORMER_BNN_DEFAULTS["feature_gate_scale"], 0.1, 3.0, 0.1, "%.1f"),
        _check("use_feature_residual", "Use Feature Residual", TRANSFORMER_BNN_DEFAULTS["use_feature_residual"]),
        _select("pooling", "Pooling", TRANSFORMER_BNN_DEFAULTS["pooling"], ["cls", "mean", "attention"]),
        _slider("head_hidden_dim", "Bayesian Head Hidden Dimension", TRANSFORMER_BNN_DEFAULTS["head_hidden_dim"], 0, 512, 32),
        _number("layer_norm_eps", "LayerNorm Epsilon", TRANSFORMER_BNN_DEFAULTS["layer_norm_eps"], 1e-6, 1e-3, 1e-6, "%.6f"),
        _select("optimizer", "Optimizer", TRANSFORMER_BNN_DEFAULTS["optimizer"], ["adamw", "adam", "sgd"]),
        _number("learning_rate", "Learning Rate", TRANSFORMER_BNN_DEFAULTS["learning_rate"], 1e-5, 2e-2, 1e-5, "%.5f"),
        _number("weight_decay", "Weight Decay", TRANSFORMER_BNN_DEFAULTS["weight_decay"], 0.0, 0.01, 0.0001, "%.4f"),
        _slider("batch_size", "Batch Size", TRANSFORMER_BNN_DEFAULTS["batch_size"], 16, 2048, 16),
        _slider("epochs", "Epochs", TRANSFORMER_BNN_DEFAULTS["epochs"], 20, 800, 20),
        _slider("patience", "Early Stopping Patience", TRANSFORMER_BNN_DEFAULTS["patience"], 5, 120, 5),
        _slider("validation_split", "Validation Split", TRANSFORMER_BNN_DEFAULTS["validation_split"], 0.0, 0.3, 0.05),
        _slider("mc_samples", "MC Samples", TRANSFORMER_BNN_DEFAULTS["mc_samples"], 5, 200, 5),
        _select("loss_name", "Loss Function", TRANSFORMER_BNN_DEFAULTS["loss_name"], ["gaussian_nll", "mse"]),
        _number("min_logvar", "Min Log-Variance", TRANSFORMER_BNN_DEFAULTS["min_logvar"], -12.0, -1.0, 0.5, "%.1f"),
        _number("max_logvar", "Max Log-Variance", TRANSFORMER_BNN_DEFAULTS["max_logvar"], 0.5, 8.0, 0.5, "%.1f"),
        _number("gradient_clip_norm", "Gradient Clipping", TRANSFORMER_BNN_DEFAULTS["gradient_clip_norm"], 0.0, 10.0, 0.5, "%.1f"),
        _slider("scheduler_factor", "LR Scheduler Factor", TRANSFORMER_BNN_DEFAULTS["scheduler_factor"], 0.1, 0.9, 0.1),
        _slider("scheduler_patience", "LR Scheduler Patience", TRANSFORMER_BNN_DEFAULTS["scheduler_patience"], 2, 30, 1),
        _number("min_learning_rate", "Minimum Learning Rate", TRANSFORMER_BNN_DEFAULTS["min_learning_rate"], 1e-7, 1e-4, 1e-7, "%.7f"),
        _select(
            "missing_value_strategy",
            "Missing Value Strategy",
            TRANSFORMER_BNN_DEFAULTS["missing_value_strategy"],
            ["median", "bayesian", "multiple_bayesian", "mask_zero"],
            "mask_zero: skip statistical imputation, keep a missing-value mask, and use zero only as a placeholder after NaN-aware scaling.",
        ),
        _slider("missing_imputer_max_iter", "Imputer Max Iterations", TRANSFORMER_BNN_DEFAULTS["missing_imputer_max_iter"], 5, 50, 1),
        _slider("missing_n_imputations", "Multiple Imputations", TRANSFORMER_BNN_DEFAULTS["missing_n_imputations"], 2, 20, 1),
        _check("use_missingness_embedding", "Use Missingness Embedding", TRANSFORMER_BNN_DEFAULTS["use_missingness_embedding"]),
        _check("use_missingness_attention", "Use Missingness Attention", TRANSFORMER_BNN_DEFAULTS["use_missingness_attention"]),
        _select("device", "Device", TRANSFORMER_BNN_DEFAULTS["device"], ["auto", "cpu", "cuda", "cuda:0", "cuda:1"]),
        _check("use_data_parallel", "Use Multi-GPU DataParallel", TRANSFORMER_BNN_DEFAULTS["use_data_parallel"], "Enable synchronous data-parallel training when multiple CUDA GPUs are available."),
        _text("gpu_ids", "GPU IDs", TRANSFORMER_BNN_DEFAULTS["gpu_ids"], "Comma-separated CUDA device IDs, for example 0,1."),
        _number("random_state", "Random Seed", TRANSFORMER_BNN_DEFAULTS["random_state"], 0, 9999, 1),
        _check("verbose", "Verbose Logging", TRANSFORMER_BNN_DEFAULTS["verbose"]),
    ],
    "Epoxy PINN (Physics-Informed)": [
        _select("mode", "PINN Mode", EPOXY_PINN_DEFAULTS["mode"], ["auto", "tg", "mechanics", "generic"]),
        _select("optimizer", "Optimizer", EPOXY_PINN_DEFAULTS["optimizer"], ["adamw", "adam", "sgd", "rmsprop"]),
        _slider("hidden_dim", "Hidden Dimension", EPOXY_PINN_DEFAULTS["hidden_dim"], 64, 1024, 64),
        _slider("n_layers", "Hidden Layers", EPOXY_PINN_DEFAULTS["n_layers"], 1, 8, 1),
        _slider("dropout", "Dropout", EPOXY_PINN_DEFAULTS["dropout"], 0.0, 0.6, 0.05),
        _number("lr", "Learning Rate", EPOXY_PINN_DEFAULTS["lr"], 1e-5, 1e-2, 1e-5, "%.5f"),
        _number("weight_decay", "Weight Decay", EPOXY_PINN_DEFAULTS["weight_decay"], 0.0, 0.01, 0.0001, "%.4f"),
        _slider("batch_size", "Batch Size", EPOXY_PINN_DEFAULTS["batch_size"], 16, 4096, 16),
        _slider("epochs", "Epochs", EPOXY_PINN_DEFAULTS["epochs"], 50, 2000, 50),
        _slider("patience", "Early Stopping Patience", EPOXY_PINN_DEFAULTS["patience"], 5, 300, 5),
        _number("physics_weight", "Physics Loss Weight", EPOXY_PINN_DEFAULTS["physics_weight"], 0.0, 0.05, 0.0001, "%.4f"),
        _select("physics_formula", "Physics Formula", EPOXY_PINN_DEFAULTS["physics_formula"], ["standard", "advanced"]),
        _number("grad_clip", "Gradient Clipping", EPOXY_PINN_DEFAULTS["grad_clip"], 0.0, 5.0, 0.5, "%.1f"),
        _select("missing_value_strategy", "Missing Value Strategy", EPOXY_PINN_DEFAULTS["missing_value_strategy"], ["median", "bayesian", "multiple_bayesian"]),
        _slider("missing_imputer_max_iter", "Imputer Max Iterations", EPOXY_PINN_DEFAULTS["missing_imputer_max_iter"], 5, 50, 1),
        _slider("missing_n_imputations", "Multiple Imputations", EPOXY_PINN_DEFAULTS["missing_n_imputations"], 2, 20, 1),
        _select("device", "Device", EPOXY_PINN_DEFAULTS["device"], ["auto", "cpu", "cuda"]),
        _check("verbose", "Verbose Logging", EPOXY_PINN_DEFAULTS["verbose"]),
        _number("seed", "Random Seed", EPOXY_PINN_DEFAULTS["seed"], 0, 9999, 1),
        _text("target_name", "Target Name", EPOXY_PINN_DEFAULTS["target_name"], "Used when mode=auto to infer the physics branch."),
    ],
    "Transformer + PINN": [
        _select("mode", "PINN Mode", TRANSFORMER_PINN_DEFAULTS["mode"], ["auto", "tg", "mechanics", "generic"]),
        _slider("d_token", "Token Dimension", TRANSFORMER_PINN_DEFAULTS["d_token"], 64, 512, 32),
        _slider("n_blocks", "Transformer Blocks", TRANSFORMER_PINN_DEFAULTS["n_blocks"], 1, 8, 1),
        _slider("attention_n_heads", "Attention Heads", TRANSFORMER_PINN_DEFAULTS["attention_n_heads"], 2, 16, 2),
        _slider("attention_dropout", "Attention Dropout", TRANSFORMER_PINN_DEFAULTS["attention_dropout"], 0.0, 0.5, 0.05),
        _slider("residual_dropout", "Residual Dropout", TRANSFORMER_PINN_DEFAULTS["residual_dropout"], 0.0, 0.4, 0.05),
        _slider("ffn_d_hidden", "FFN Hidden Dimension", TRANSFORMER_PINN_DEFAULTS["ffn_d_hidden"], 128, 2048, 128),
        _slider("ffn_dropout", "FFN Dropout", TRANSFORMER_PINN_DEFAULTS["ffn_dropout"], 0.0, 0.5, 0.05),
        _slider("token_dropout", "Token Dropout", TRANSFORMER_PINN_DEFAULTS["token_dropout"], 0.0, 0.3, 0.05),
        _select("activation", "Activation", TRANSFORMER_PINN_DEFAULTS["activation"], ["gelu", "relu", "silu", "elu", "tanh", "leaky_relu"]),
        _slider("sub_attention_dim", "Sub-Attention Hidden Dimension", TRANSFORMER_PINN_DEFAULTS["sub_attention_dim"], 16, 256, 16),
        _slider("sub_attention_dropout", "Sub-Attention Dropout", TRANSFORMER_PINN_DEFAULTS["sub_attention_dropout"], 0.0, 0.5, 0.05),
        _number("sub_attention_temperature", "Sub-Attention Temperature", TRANSFORMER_PINN_DEFAULTS["sub_attention_temperature"], 0.2, 3.0, 0.1, "%.1f"),
        _select("feature_gate_type", "Feature Gate Type", TRANSFORMER_PINN_DEFAULTS["feature_gate_type"], ["softmax", "sigmoid"]),
        _number("feature_gate_scale", "Feature Gate Scale", TRANSFORMER_PINN_DEFAULTS["feature_gate_scale"], 0.1, 3.0, 0.1, "%.1f"),
        _check("use_feature_residual", "Use Feature Residual", TRANSFORMER_PINN_DEFAULTS["use_feature_residual"]),
        _select("pooling", "Pooling", TRANSFORMER_PINN_DEFAULTS["pooling"], ["cls", "mean", "attention"]),
        _slider("head_hidden_dim", "Prediction Head Hidden Dimension", TRANSFORMER_PINN_DEFAULTS["head_hidden_dim"], 0, 512, 32),
        _number("layer_norm_eps", "LayerNorm Epsilon", TRANSFORMER_PINN_DEFAULTS["layer_norm_eps"], 1e-6, 1e-3, 1e-6, "%.6f"),
        _select("optimizer", "Optimizer", TRANSFORMER_PINN_DEFAULTS["optimizer"], ["adamw", "adam", "sgd", "rmsprop"]),
        _number("lr", "Learning Rate", TRANSFORMER_PINN_DEFAULTS["lr"], 1e-5, 1e-2, 1e-5, "%.5f"),
        _number("weight_decay", "Weight Decay", TRANSFORMER_PINN_DEFAULTS["weight_decay"], 0.0, 0.01, 0.0001, "%.4f"),
        _slider("batch_size", "Batch Size", TRANSFORMER_PINN_DEFAULTS["batch_size"], 16, 2048, 16),
        _slider("epochs", "Epochs", TRANSFORMER_PINN_DEFAULTS["epochs"], 50, 1200, 25),
        _slider("patience", "Early Stopping Patience", TRANSFORMER_PINN_DEFAULTS["patience"], 5, 200, 5),
        _number("physics_weight", "Physics Loss Weight", TRANSFORMER_PINN_DEFAULTS["physics_weight"], 0.0, 0.05, 0.0001, "%.4f"),
        _select("physics_formula", "Physics Formula", TRANSFORMER_PINN_DEFAULTS["physics_formula"], ["standard", "advanced"]),
        _number("grad_clip", "Gradient Clipping", TRANSFORMER_PINN_DEFAULTS["grad_clip"], 0.0, 5.0, 0.5, "%.1f"),
        _select("missing_value_strategy", "Missing Value Strategy", TRANSFORMER_PINN_DEFAULTS["missing_value_strategy"], ["median", "bayesian", "multiple_bayesian"]),
        _slider("missing_imputer_max_iter", "Imputer Max Iterations", TRANSFORMER_PINN_DEFAULTS["missing_imputer_max_iter"], 5, 50, 1),
        _slider("missing_n_imputations", "Multiple Imputations", TRANSFORMER_PINN_DEFAULTS["missing_n_imputations"], 2, 20, 1),
        _check("use_missingness_embedding", "Use Missingness Embedding", TRANSFORMER_PINN_DEFAULTS["use_missingness_embedding"]),
        _check("use_missingness_attention", "Use Missingness Attention", TRANSFORMER_PINN_DEFAULTS["use_missingness_attention"]),
        _select("device", "Device", TRANSFORMER_PINN_DEFAULTS["device"], ["auto", "cpu", "cuda"]),
        _check("verbose", "Verbose Logging", TRANSFORMER_PINN_DEFAULTS["verbose"]),
        _number("seed", "Random Seed", TRANSFORMER_PINN_DEFAULTS["seed"], 0, 9999, 1),
        _text("target_name", "Target Name", TRANSFORMER_PINN_DEFAULTS["target_name"], "Used when mode=auto to infer the physics branch."),
    ],
    "GNN + Transformer Fusion": [
        _select("graph_model_type", "Graph Encoder", GNN_TRANSFORMER_FUSION_DEFAULTS["graph_model_type"], ["gcn", "gat", "gin", "graphsage", "mpnn"]),
        _slider("graph_hidden_dim", "Graph Hidden Dimension", GNN_TRANSFORMER_FUSION_DEFAULTS["graph_hidden_dim"], 64, 512, 32),
        _slider("graph_num_layers", "Graph Layers", GNN_TRANSFORMER_FUSION_DEFAULTS["graph_num_layers"], 1, 6, 1),
        _slider("graph_dropout", "Graph Dropout", GNN_TRANSFORMER_FUSION_DEFAULTS["graph_dropout"], 0.0, 0.5, 0.05),
        _select("graph_pooling", "Graph Pooling", GNN_TRANSFORMER_FUSION_DEFAULTS["graph_pooling"], ["mean", "add"]),
        _slider("gat_heads", "GAT Heads", GNN_TRANSFORMER_FUSION_DEFAULTS["gat_heads"], 2, 12, 2),
        _slider("d_token", "Tabular Token Dimension", GNN_TRANSFORMER_FUSION_DEFAULTS["d_token"], 64, 512, 32),
        _slider("n_blocks", "Tabular Transformer Blocks", GNN_TRANSFORMER_FUSION_DEFAULTS["n_blocks"], 1, 8, 1),
        _slider("attention_n_heads", "Tabular Attention Heads", GNN_TRANSFORMER_FUSION_DEFAULTS["attention_n_heads"], 2, 16, 2),
        _slider("attention_dropout", "Attention Dropout", GNN_TRANSFORMER_FUSION_DEFAULTS["attention_dropout"], 0.0, 0.5, 0.05),
        _slider("residual_dropout", "Residual Dropout", GNN_TRANSFORMER_FUSION_DEFAULTS["residual_dropout"], 0.0, 0.4, 0.05),
        _slider("ffn_d_hidden", "FFN Hidden Dimension", GNN_TRANSFORMER_FUSION_DEFAULTS["ffn_d_hidden"], 128, 2048, 128),
        _slider("ffn_dropout", "FFN Dropout", GNN_TRANSFORMER_FUSION_DEFAULTS["ffn_dropout"], 0.0, 0.5, 0.05),
        _slider("token_dropout", "Token Dropout", GNN_TRANSFORMER_FUSION_DEFAULTS["token_dropout"], 0.0, 0.3, 0.05),
        _select("activation", "Activation", GNN_TRANSFORMER_FUSION_DEFAULTS["activation"], ["gelu", "relu", "silu", "elu", "tanh", "leaky_relu"]),
        _slider("sub_attention_dim", "Sub-Attention Hidden Dimension", GNN_TRANSFORMER_FUSION_DEFAULTS["sub_attention_dim"], 16, 256, 16),
        _slider("sub_attention_dropout", "Sub-Attention Dropout", GNN_TRANSFORMER_FUSION_DEFAULTS["sub_attention_dropout"], 0.0, 0.5, 0.05),
        _number("sub_attention_temperature", "Sub-Attention Temperature", GNN_TRANSFORMER_FUSION_DEFAULTS["sub_attention_temperature"], 0.2, 3.0, 0.1, "%.1f"),
        _select("feature_gate_type", "Feature Gate Type", GNN_TRANSFORMER_FUSION_DEFAULTS["feature_gate_type"], ["softmax", "sigmoid"]),
        _number("feature_gate_scale", "Feature Gate Scale", GNN_TRANSFORMER_FUSION_DEFAULTS["feature_gate_scale"], 0.1, 3.0, 0.1, "%.1f"),
        _check("use_feature_residual", "Use Feature Residual", GNN_TRANSFORMER_FUSION_DEFAULTS["use_feature_residual"]),
        _select("transformer_pooling", "Tabular Pooling", GNN_TRANSFORMER_FUSION_DEFAULTS["transformer_pooling"], ["cls", "mean", "attention"]),
        _slider("fusion_hidden_dim", "Fusion Head Hidden Dimension", GNN_TRANSFORMER_FUSION_DEFAULTS["fusion_hidden_dim"], 64, 1024, 64),
        _number("layer_norm_eps", "LayerNorm Epsilon", GNN_TRANSFORMER_FUSION_DEFAULTS["layer_norm_eps"], 1e-6, 1e-3, 1e-6, "%.6f"),
        _number("learning_rate", "Learning Rate", GNN_TRANSFORMER_FUSION_DEFAULTS["learning_rate"], 1e-5, 1e-2, 1e-5, "%.5f"),
        _number("weight_decay", "Weight Decay", GNN_TRANSFORMER_FUSION_DEFAULTS["weight_decay"], 0.0, 0.01, 0.0001, "%.4f"),
        _slider("batch_size", "Batch Size", GNN_TRANSFORMER_FUSION_DEFAULTS["batch_size"], 4, 256, 4),
        _slider("epochs", "Epochs", GNN_TRANSFORMER_FUSION_DEFAULTS["epochs"], 20, 400, 20),
        _slider("patience", "Early Stopping Patience", GNN_TRANSFORMER_FUSION_DEFAULTS["patience"], 5, 120, 5),
        _slider("validation_split", "Validation Split", GNN_TRANSFORMER_FUSION_DEFAULTS["validation_split"], 0.0, 0.3, 0.05),
        _select("loss_name", "Loss Function", GNN_TRANSFORMER_FUSION_DEFAULTS["loss_name"], ["mse", "huber", "mae"]),
        _number("gradient_clip_norm", "Gradient Clipping", GNN_TRANSFORMER_FUSION_DEFAULTS["gradient_clip_norm"], 0.0, 10.0, 0.5, "%.1f"),
        _slider("scheduler_factor", "LR Scheduler Factor", GNN_TRANSFORMER_FUSION_DEFAULTS["scheduler_factor"], 0.1, 0.9, 0.1),
        _slider("scheduler_patience", "LR Scheduler Patience", GNN_TRANSFORMER_FUSION_DEFAULTS["scheduler_patience"], 2, 30, 1),
        _number("min_learning_rate", "Minimum Learning Rate", GNN_TRANSFORMER_FUSION_DEFAULTS["min_learning_rate"], 1e-7, 1e-4, 1e-7, "%.7f"),
        _select("missing_value_strategy", "Missing Value Strategy", GNN_TRANSFORMER_FUSION_DEFAULTS["missing_value_strategy"], ["median", "bayesian", "multiple_bayesian"]),
        _slider("missing_imputer_max_iter", "Imputer Max Iterations", GNN_TRANSFORMER_FUSION_DEFAULTS["missing_imputer_max_iter"], 5, 50, 1),
        _slider("missing_n_imputations", "Multiple Imputations", GNN_TRANSFORMER_FUSION_DEFAULTS["missing_n_imputations"], 2, 20, 1),
        _check("use_missingness_embedding", "Use Missingness Embedding", GNN_TRANSFORMER_FUSION_DEFAULTS["use_missingness_embedding"]),
        _check("use_missingness_attention", "Use Missingness Attention", GNN_TRANSFORMER_FUSION_DEFAULTS["use_missingness_attention"]),
        _slider("num_workers", "DataLoader Workers", GNN_TRANSFORMER_FUSION_DEFAULTS["num_workers"], 0, 8, 1),
        _select("device", "Device", GNN_TRANSFORMER_FUSION_DEFAULTS["device"], ["auto", "cpu", "cuda"]),
        _number("random_state", "Random Seed", GNN_TRANSFORMER_FUSION_DEFAULTS["random_state"], 0, 9999, 1),
        _slider("verbose", "Verbose Level", GNN_TRANSFORMER_FUSION_DEFAULTS["verbose"], 0, 2, 1),
    ],
    "TabNet": [
        _slider("n_d", "Decision Dimension", TABNET_DEFAULTS["n_d"], 8, 128, 8),
        _slider("n_a", "Attention Dimension", TABNET_DEFAULTS["n_a"], 8, 128, 8),
        _slider("n_steps", "Decision Steps", TABNET_DEFAULTS["n_steps"], 3, 10, 1),
        _number("gamma", "Feature Reuse Coefficient", TABNET_DEFAULTS["gamma"], 1.0, 2.0, 0.1, "%.1f"),
        _slider("n_independent", "Independent GLU Layers", TABNET_DEFAULTS["n_independent"], 1, 5, 1),
        _slider("n_shared", "Shared GLU Layers", TABNET_DEFAULTS["n_shared"], 1, 5, 1),
        _number("lambda_sparse", "Sparsity Regularization", TABNET_DEFAULTS["lambda_sparse"], 0.0, 0.01, 1e-5, "%.5f"),
        _number("momentum", "BatchNorm Momentum", TABNET_DEFAULTS["momentum"], 0.01, 0.1, 0.01, "%.2f"),
        _number("clip_value", "Gradient Clipping", TABNET_DEFAULTS["clip_value"], 0.5, 5.0, 0.5, "%.1f"),
        _number("learning_rate", "Learning Rate", TABNET_DEFAULTS["learning_rate"], 0.0001, 0.05, 0.0001, "%.4f"),
        _slider("max_epochs", "Max Epochs", TABNET_DEFAULTS["max_epochs"], 50, 500, 25),
        _slider("patience", "Early Stopping Patience", TABNET_DEFAULTS["patience"], 5, 100, 5),
        _slider("batch_size", "Batch Size", TABNET_DEFAULTS["batch_size"], 64, 4096, 64),
        _slider("virtual_batch_size", "Virtual Batch Size", TABNET_DEFAULTS["virtual_batch_size"], 16, 512, 16),
        _select("mask_type", "Mask Type", TABNET_DEFAULTS["mask_type"], ["sparsemax", "entmax"]),
        _number("seed", "Random Seed", TABNET_DEFAULTS["seed"], 0, 9999, 1),
    ],
    "TensorFlow Sequential": [],
    "TabPFN": [],
    "AutoGluon": [
        _slider("time_limit", "Time Limit (s)", AUTOGLUON_DEFAULTS["time_limit"], 30, 3600, 30),
        _select("presets", "Presets", AUTOGLUON_DEFAULTS["presets"], ["medium_quality", "best_quality", "high_quality", "good_quality"]),
        _slider("num_gpus", "Number of GPUs", AUTOGLUON_DEFAULTS["num_gpus"], 0, 8, 1),
        _slider("num_cpus", "Number of CPUs", AUTOGLUON_DEFAULTS["num_cpus"], 0, 64, 1),
    ],
    "Auto-sklearn": [
        _slider("time_left_for_this_task", "Total Search Time (s)", AUTOSKLEARN_DEFAULTS["time_left_for_this_task"], 60, 1800, 60),
        _slider("per_run_time_limit", "Per-Model Time Limit (s)", AUTOSKLEARN_DEFAULTS["per_run_time_limit"], 10, 600, 10),
        _slider("ensemble_size", "Ensemble Size", AUTOSKLEARN_DEFAULTS["ensemble_size"], 10, 200, 10),
    ],
    "TPOT": [
        _slider("max_time_mins", "Total Search Time (min)", TPOT_DEFAULTS["max_time_mins"], 1, 60, 1),
        _slider("max_eval_time_mins", "Per-Model Time Limit (min)", TPOT_DEFAULTS["max_eval_time_mins"], 1, 30, 1),
        _slider("generations", "Generations", TPOT_DEFAULTS["generations"], 1, 50, 1),
        _slider("population_size", "Population Size", TPOT_DEFAULTS["population_size"], 10, 200, 10),
    ],
    "FLAML": [
        _slider("time_budget", "Time Budget (s)", FLAML_DEFAULTS["time_budget"], 30, 1800, 30),
        _select("metric", "Optimization Metric", FLAML_DEFAULTS["metric"], ["r2", "rmse", "mae"]),
    ],
    "Chemical SuperLearner (ChemSL)": [
        _slider("n_estimators", "Base Estimator Trees", CHEMSL_DEFAULTS["n_estimators"], 50, 500, 50),
        _check("fast_mode", "Fast Mode", CHEMSL_DEFAULTS["fast_mode"], "Reduce search cost automatically on larger datasets."),
        _slider("max_depth", "Max Depth (0=None)", CHEMSL_DEFAULTS["max_depth"], 0, 20, 1),
        _slider("min_estimators", "Minimum Trees", CHEMSL_DEFAULTS["min_estimators"], 20, 200, 10),
    ],
    "fastprop": [
        _slider("max_iter", "Iterations", FASTPROP_DEFAULTS["max_iter"], 50, 1000, 50),
        _number("learning_rate", "Learning Rate", FASTPROP_DEFAULTS["learning_rate"], 0.001, 0.2, 0.001, "%.3f"),
        _slider("max_depth", "Max Depth", FASTPROP_DEFAULTS["max_depth"], 2, 16, 1),
        _number("l2_regularization", "L2 Regularization", FASTPROP_DEFAULTS["l2_regularization"], 0.0, 1.0, 0.01, "%.2f"),
    ],
}


RECOMMENDED_PRESETS = {
    "随机森林": {
        "Small dataset": {
            "desc": "Reduce tree depth and bootstrap more conservatively to resist overfitting on limited data.",
            "params": {
                "n_estimators": 300,
                "max_depth": 8,
                "min_samples_split": 5,
                "min_samples_leaf": 3,
                "max_features": "sqrt",
                "bootstrap": True,
                "max_samples": 0.8,
                "oob_score": True,
                "verbose": 1,
            },
        },
        "Medium dataset": {
            "desc": "Balanced random-forest preset for most CFRP and resin tabular datasets.",
            "params": {
                "n_estimators": 500,
                "max_depth": 15,
                "min_samples_split": 3,
                "min_samples_leaf": 2,
                "max_features": 0.7,
                "bootstrap": True,
                "max_samples": 0.9,
                "oob_score": True,
                "verbose": 1,
            },
        },
    },
    "Extra Trees": {
        "Balanced": {
            "desc": "Default high-throughput tree preset with stronger randomness and good speed.",
            "params": {
                "n_estimators": 500,
                "max_depth": 15,
                "min_samples_split": 3,
                "min_samples_leaf": 2,
                "max_features": 0.7,
                "bootstrap": False,
            },
        },
    },
    "XGBoost": {
        "Small dataset": {
            "desc": "Lower learning rate and stronger regularization for limited-sample settings.",
            "params": {
                "n_estimators": 500,
                "max_depth": 4,
                "learning_rate": 0.05,
                "subsample": 0.8,
                "colsample_bytree": 0.8,
                "min_child_weight": 5,
                "gamma": 0.0,
                "reg_alpha": 0.1,
                "reg_lambda": 1.0,
                "eval_metric": "rmse",
            },
        },
        "Medium / large dataset": {
            "desc": "Stronger capacity for broader datasets while keeping regularization moderate.",
            "params": {
                "n_estimators": 1000,
                "max_depth": 6,
                "learning_rate": 0.1,
                "subsample": 0.9,
                "colsample_bytree": 0.8,
                "min_child_weight": 3,
                "gamma": 0.0,
                "reg_alpha": 0.0,
                "reg_lambda": 1.0,
                "eval_metric": "rmse",
            },
        },
    },
    "LightGBM": {
        "Small dataset": {
            "desc": "Restrict leaves and use stronger regularization to stabilize smaller samples.",
            "params": {
                "n_estimators": 500,
                "max_depth": 5,
                "learning_rate": 0.05,
                "num_leaves": 31,
                "subsample": 0.8,
                "colsample_bytree": 0.8,
                "reg_alpha": 0.1,
                "reg_lambda": 1.0,
                "min_child_samples": 10,
            },
        },
        "Medium / large dataset": {
            "desc": "Balanced LightGBM preset for broader tabular regression workloads.",
            "params": {
                "n_estimators": 1000,
                "max_depth": 7,
                "learning_rate": 0.1,
                "num_leaves": 63,
                "subsample": 0.9,
                "colsample_bytree": 0.8,
                "reg_alpha": 0.0,
                "reg_lambda": 0.0,
                "min_child_samples": 20,
            },
        },
    },
    "CatBoost": {
        "Balanced": {
            "desc": "Strong default CatBoost preset for structured materials data with moderate noise.",
            "params": {
                "iterations": 800,
                "depth": 6,
                "learning_rate": 0.05,
                "l2_leaf_reg": 3.0,
                "subsample": 0.9,
                "bagging_temperature": 1.0,
                "loss_function": "RMSE",
            },
        },
    },
    "Bayesian Neural Network (BNN)": {
        "Stable uncertainty": {
            "desc": "Balanced BNN preset for medium tabular datasets with calibrated predictive variance.",
            "params": dict(BNN_DEFAULTS),
        },
        "Deeper hidden stack": {
            "desc": "More capacity with BatchNorm enabled for richer nonlinear structure.",
            "params": {
                **BNN_DEFAULTS,
                "hidden_layer_sizes": "512,256,128",
                "activation": "gelu",
                "dropout_rate": 0.1,
                "use_batch_norm": True,
                "learning_rate": 0.0008,
                "weight_decay": 0.0002,
                "epochs": 260,
                "patience": 35,
                "mc_samples": 80,
            },
        },
    },
    "FT-Transformer": {
        "Balanced attention": {
            "desc": "Recommended starting point for most medium-scale tabular regression tasks.",
            "params": dict(FT_TRANSFORMER_DEFAULTS),
        },
        "Deeper attention": {
            "desc": "Higher-capacity FT-Transformer for larger datasets or more complex feature interactions.",
            "params": {
                **FT_TRANSFORMER_DEFAULTS,
                "d_token": 192,
                "n_blocks": 6,
                "ffn_d_hidden": 512,
                "ffn_dropout": 0.15,
                "token_dropout": 0.1,
                "sub_attention_dim": 96,
                "feature_gate_scale": 1.2,
                "pooling": "attention",
                "head_hidden_dim": 192,
                "learning_rate": 0.0008,
                "epochs": 220,
                "patience": 25,
                "loss_name": "huber",
            },
        },
    },
    "Transformer + BNN": {
        "Balanced hybrid": {
            "desc": "Good default when you want both feature interaction modeling and predictive uncertainty.",
            "params": dict(TRANSFORMER_BNN_DEFAULTS),
        },
        "Uncertainty-focused": {
            "desc": "Slightly deeper encoder with more MC samples for more stable uncertainty estimates.",
            "params": {
                **TRANSFORMER_BNN_DEFAULTS,
                "d_token": 160,
                "n_blocks": 5,
                "ffn_d_hidden": 384,
                "ffn_dropout": 0.15,
                "sub_attention_dim": 96,
                "head_hidden_dim": 160,
                "learning_rate": 0.0008,
                "weight_decay": 0.0002,
                "epochs": 240,
                "patience": 35,
                "mc_samples": 80,
            },
        },
    },
    "Epoxy PINN (Physics-Informed)": {
        "Physics balanced": {
            "desc": "General-purpose PINN preset for Tg-oriented materials datasets.",
            "params": dict(EPOXY_PINN_DEFAULTS),
        },
        "Stronger physics": {
            "desc": "Increase physics regularization when the dataset is noisy but mechanistic priors are reliable.",
            "params": {
                **EPOXY_PINN_DEFAULTS,
                "hidden_dim": 896,
                "n_layers": 6,
                "dropout": 0.30,
                "lr": 0.00015,
                "weight_decay": 0.0004,
                "epochs": 1800,
                "patience": 180,
                "physics_weight": 0.003,
                "physics_formula": "advanced",
                "grad_clip": 1.5,
            },
        },
    },
    "Transformer + PINN": {
        "Physics balanced": {
            "desc": "Recommended hybrid preset for Tg or modulus tasks that need both transformer feature modeling and physics loss.",
            "params": dict(TRANSFORMER_PINN_DEFAULTS),
        },
        "Stronger physics": {
            "desc": "Increase physics weight and encoder capacity when physical priors should dominate more strongly.",
            "params": {
                **TRANSFORMER_PINN_DEFAULTS,
                "d_token": 160,
                "n_blocks": 5,
                "ffn_d_hidden": 384,
                "ffn_dropout": 0.15,
                "sub_attention_dim": 96,
                "head_hidden_dim": 160,
                "lr": 0.0008,
                "weight_decay": 0.0002,
                "epochs": 500,
                "patience": 80,
                "physics_weight": 0.005,
                "physics_formula": "advanced",
                "grad_clip": 1.0,
            },
        },
    },
    "GNN + Transformer Fusion": {
        "Balanced fusion": {
            "desc": "Use graph structure from SMILES and numeric process features with moderate model size.",
            "params": dict(GNN_TRANSFORMER_FUSION_DEFAULTS),
        },
        "Higher-capacity fusion": {
            "desc": "Larger graph and tabular branches for datasets with enough samples and richer structure.",
            "params": {
                **GNN_TRANSFORMER_FUSION_DEFAULTS,
                "graph_model_type": "gat",
                "graph_hidden_dim": 192,
                "graph_num_layers": 4,
                "graph_dropout": 0.15,
                "d_token": 192,
                "n_blocks": 5,
                "ffn_d_hidden": 512,
                "ffn_dropout": 0.15,
                "sub_attention_dim": 96,
                "fusion_hidden_dim": 384,
                "learning_rate": 0.0008,
                "weight_decay": 0.0002,
                "batch_size": 24,
                "epochs": 160,
                "patience": 25,
                "loss_name": "huber",
            },
        },
    },
}
